<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div id="finder" class="dialogelfinder"></div>
<script type="text/javascript">
    var base_media_url = "<?= $this->getBaseMediaUrl() ?>";
    var base_secure_media_url = "<?= $this->getBaseSecureMediaUrl() ?>";
    var elfinder_connector = "<?= $this->getConnectorUrl(); ?>";
    require(['jquery'],function($){
        $(document).ready(function(){
        require([
                'jquery',
                'Ves_BaseWidget/js/jquery/ui/jquery-ui.min',
                'Ves_BaseWidget/js/elfinder/js/elfinder.min',
            ], function(jQuery){
                console.log("\n Connector: <?= $this->getConnectorUrl(); ?>");
                var f = jQuery('#finder').elfinder({
                        url : '<?= $this->getConnectorUrl(); ?>'
                    }).elfinder('instance');
            });
        });
    });
</script>
