<?php
$id = rand().time();
if (isset($accordions)): ?>
<!-- Accordion with background -->
<div class="ves-widget widget-accordion-bg block <?= $addition_cls; ?> <?php if (isset($stylecls)&&$stylecls) echo 'block-'.$stylecls;?>">
	<?php if (isset($widget_heading)&&!empty($widget_heading)): ?>
	<div class="block-title">
		<h2><span><?= $widget_heading; ?></span></h2>
	</div>
	<?php endif; ?>
	<div class="widget-inner block-content">
		<div id="accordion<?= $id; ?>" class="panel-menu accordian-play">
	 	<?php foreach ($accordions as $key => $ac): ?>
	 		<?php
	 			$item_class = (isset($ac['class']) && $ac['class']) ?$ac['class']: "accordion-item-".$key;
	 			$item_background = (isset($ac['image']) && $ac['image']) ? ' background-image: url('. $ac['image'] .');' : "";
	 		?>
			<!-- accodion item -->
			<div class="menu-title closed <?= $item_class; ?>" data-menu="<?= $item_class; ?>" <?php if(empty($item_background)): ?>  data-bg-effect="0" <?php endif; ?>>
				<h<?= $heading_type; ?>><?= $ac['header']; ?></h<?= $heading_type; ?>><i class="icon-open-close"></i>
				<div class="bg" style="<?= $item_background; ?>"></div>
			</div>
			<div class="panel-item-content" data-menu="<?= $item_class; ?>">
				<?= $ac['content']; ?>
			</div>
	 	<?php endforeach; ?>
		</div>
	</div>
</div>
<script type="text/javascript">
require(['jquery'],function($){
        $(document).ready(function(){
        	require([
				'jquery',
				'Ves_BaseWidget/js/jquery/jquery.transition',
				'Ves_BaseWidget/js/jquery/accordion'
				],function($){

				});
        })
})
</script>
<!-- End accordion with background -->
<?php endif; ?>


