<?php

$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_rule = $this->getRule();
if($_rule) {
$title_name = $this->getConfig('title_name');
$show_code = $this->getConfig('show_code');
$show_short_description = $this->getConfig('show_short_description');
$addition_cls = $this->getConfig('addition_cls');
$title = $this->getConfig('title');
$background_color = $this->getConfig('background_color');
$thumbnailurl = isset($thumbnailurl)?$thumbnailurl:"";
$style = '';
if ($background_color != '' || $thumbnailurl != '') {
    $style = 'style="';
    if($background_color != ''){
        $style .= 'background-color:'.$background_color.';';
    }

    /** THUMBNAIL **/
    $imagesize = $this->getConfig('image_size');
    $image_file = $this->getConfig('file');
    $array_size = $imagesize ? @explode("x", $imagesize) : [];
    $image_width = isset($array_size[0])?(int)$array_size[0]:0;
    $image_width = $image_width?$image_width: 0;
    $image_height = isset($array_size[1])?(int)$array_size[1]:0;
    $image_height = $image_height?$image_height: 0;
    $thumbnailurl = "";
    if($image_file ) {
        if (!preg_match("/^http\:\/\/|https\:\/\//", $image_file) && $image_width >0 && $image_height > 0) {
            $thumbnailurl = $this->getImageHelper()->resizeImage($image_file, (int)$image_width, (int)$image_height);
        } else {
            $thumbnailurl = $this->getBaseMediaUrl().$image_file;
        }
    }
    if( $thumbnailurl != '' ){

        $position_x = 'center';
        if($this->getConfig('background_position_x') != ''){
            $position_x = $this->getData('background_position_x');
        }

        $position_y = 'center';
        if($this->getConfig('background_position_y') != ''){
            $position_y = $this->getData('background_position_y');
        }

        $style .= "background-image:url('".$thumbnailurl."');background-repeat: no-repeat;";
        $style .= 'background-position: '.$position_x.' '.$position_y.';';
    }

    $style .= 'float: right;width: 100%;';

    $style .= '"';
}
$id = rand().time();
$customer_group_ids = $_rule->getCustomerGroupIds();
?>
<?php if($this->checkGroupCustomer($customer_group_ids)){ ?>
<div class="ves-widget widget-banner-countdown block <?= $addition_cls; ?> " <?= $style; ?>>
    <?php if( $title != '' ){ ?>
    <div class="block-title">
        <strong><span><?= $title; ?></span></strong>
    </div>
    <?php } ?>
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-md-8">
        <?= __($title_name).'  :';?>  <?= $_rule->getName(); ?> .
        <?php if($show_code){
                $primarycoupon = $_rule->getPrimaryCoupon();
                if($coupon_code = $primarycoupon->getCode()){
                    echo __('Use Code: ').'<strong class="coupon-code">'.$coupon_code.'</strong>';
                }else{
                    echo __('Use Code: ').'<strong class="coupon-code">'.$this->getConfig('custom_couponcode').'</strong>';
                }
            }?>
        <br>
        <?php if ($show_short_description) { ?>
            <span class="description">
            <?= __($_rule->getDescription()); ?>
            </span>
        <?php } ?>

      </div>
      <div class="col-xs-6 col-md-4">
       <!-- TIME -->
       <?php
       if($this->getConfig('show_timer_countdown')){
        $date1 = date('G:i:s', @strtotime($_rule->getToDate()));
        if ($date1 == "0:00:00") {
            $targetDate = date('m/d/Y \2\3\:\5\9\:\0\0', @strtotime($_rule->getToDate()));
        }else{
            $targetDate = date('m/d/Y G:i:s', @strtotime($_rule->getToDate()));
        }
        ?>
        <div class="banner-countdowns" >
            <div id="item<?= $id; ?>countdown_<?= $_rule->getId(); ?>" class="item-countdown"></div>
            <script type="text/javascript">
            require(['jquery','Ves_BaseWidget/js/countdown'],function ($) {
                jQuery("#item<?= $id; ?>countdown_<?= $_rule->getId(); ?>").lofCountDown({
                    formatStyle:2,
                    TargetDate:"<?= $targetDate; ?>",
                    DisplayFormat:"<ul><li>%%D%% <div><?= __('Day');?></div></li><li> %%H%% <div><?= __('Hours');?></div></li><li> %%M%% <div><?= __('Mins');?></div></li><li> %%S%% <div><?= __('Secs');?></div></li></ul>",
                    FinishMessage:"<?= __('Expired');?>",
                });

            });
            </script>
        </div>
        <?php } ?>
    </div>
</div>
</div>
<?php
} // end if check groupcustomer
} // end if check rule
?>
