<?php
$addition_cls = $this->getConfig('addition_cls');
$author =  $this->getConfig('author', "");
$cite =  $this->getConfig('cite', "");
$content = $this->getConfig('html');

$content = @str_replace(" ", "+", $content);
$content = base64_decode($content);
$content = $this->getDataFilterHelper()->filter($content);
if ($content):
?>
	<blockquote class="<?= $addition_cls; ?>">
		<?= $content; ?>
		<small><?= $author; ?><?php if($cite):?> <cite><?= $cite; ?></cite><?php endif; ?></small>
	</blockquote>
<?php endif;?>
