<?php
$cols =  (int)$this->getConfig( "columns" );
$cols = !empty($cols)?$cols:1;
$span = 12/$cols;
?>
<div class="ves-widget widget-categories-info block <?= $addition_cls; ?> <?php if (isset($stylecls)&&$stylecls) echo 'block-'.$stylecls;?>">
		<?php if (isset($widget_heading)&&!empty($widget_heading)): ?>
		<div class="block-title">
			<h2><span><?= $widget_heading; ?></span></h2>
		</div>
		<?php endif; ?>
		<!-- Show pretext -->
		<?php if( $pretext && !$cms ) { ?>
		<div class="pretext"><?= $pretext;?></div>
		<?php } elseif($cms) { ?>
		<div class="pretext"><?= $cms;?></div>
		<?php } ?>
		<!-- End Show pretext -->

	<div class="widget-inner block-content">
		<?php

		if(isset($catsid) && $catsid!= '') {

			$_catalogCatgoryHelper = $this->helper('Magento\Catalog\Helper\Category');
			$catIds = $catId ? @explode(',', $catsid) : [];
			$number_check_limit = 1;
			?>
			<?php foreach($catIds as $catId):
			$category = $this->getCategoryInfo($catId);
			if( $number_check_limit <= $limit ):?>
			<div class="col-lg-<?= $span;?> col-md-<?= $span;?> col-sm-<?= $span;?> col-xs-12">
				<div class="item">
					<div class="row">
					<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
						<?php if( $show_image && $category->getImage()){ ?>
							<div class="image pull-right" style="width:100%">
								<a href="<?= $_catalogCatgoryHelper->getCategoryUrl($category)?>" title="<?= $category->getName()?>">
									<?php
										$category_image = $this->getBaseUrl() .$category->getImage();
										if($resize_image) {
											$category_image = $this->getCategoryImage( $category, $image_width, $image_height, "thumbnail" );
										}
									?>
									<img src="<?= $category_image; ?>" width="<?= (int)$image_width; ?>" height="<?= (int)$image_height; ?>" alt="<?= $category->getName()?>">
								</a>
							</div>
						<?php } ?>
					</div>
					<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
						<?php if( $show_title ){ ?>
						<h3><a href="<?= $_catalogCatgoryHelper->getCategoryUrl($category)?>" title="<?= $category->getName(); ?>">
							<?= $category->getName()?>
							<?php if($show_number_product): ?>
								(<?= $category->getProductCount() ?>)
							<?php endif; ?>
						</a></h3>
						<?php } ?>
						<?php if( $show_description &&  $category->getDescription() != '' ){ ?>
						<div>
							<?= $this->subString($category->getDescription(), $limit_description); ?>
						</div>
						<?php } ?>
						<?php
						/*Returns comma separated ids*/
						$subCatIds = $category->getChildren();
						if($subCatIds != '' && $show_sub_category ){
							?>
							<ul>
								<?php
								$c = 0;
                                $subCatIdsArr = $subCatIds ? @explode(',', $subCatIds) : [];
								foreach($subCatIdsArr as $subCat) :?>
								<?php if( $c == $limit_subcategory ) break; ?>
								<li>
									<?php
									$subCategory = $this->getCategoryInfo($subCat);
									?>
									<a href="<?= $_catalogCatgoryHelper->getCategoryUrl($subCategory)?>" title="<?= $subCategory->getName() ?>">
										<?= $subCategory->getName() ?>
										<?php if( $show_number_product ){
											echo '('.$subCategory->getProductCount().')';
										} ?>
									</a>
								</li>
								<?php $c++; ?>
							<?php endforeach; ?>
						</ul>
						<?php } ?>

						<?php if( $show_viewall ){ ?>
						<div class="view">
							<a href="<?= $_catalogCatgoryHelper->getCategoryUrl($category)?>" title="<?= __('View all'); ?>"><?= __('View all'); ?></a>
						</div>
						<?php } ?>
					</div>
				</div>
				</div>
			</div>
		<?php endif; ?>
		<?php $number_check_limit ++ ?>
	<?php endforeach; ?>
	<?php } ?>
</div>
<div class="clearfix clr"> </div>
</div>
