<?php
	$modid = rand().time();
	$enable_collapse = $this->getConfig("enable_collapse", 0);
	$custom_id = $this->getConfig("custom_id", "");
	$speed = $speed?(int)$speed:200;
?>
<div <?= $custom_id?'id="'.$custom_id.'"':''; ?> class="ves-widget block block-list block-flickr-widget">
	<?php if(isset($title) && @trim($title)!=''): ?>
		<div class="block-title">
			<?php if($enable_collapse): ?><span class="opener hidden-lg hidden-md" data-toggle="collapse" data-target="#widget-flickr<?= $modid; ?>"><i class="fa fa-angle-down"></i></span><?php endif; ?>
			<strong><span><?= $title; ?></span></strong>
		</div>
	<?php endif; ?>

<div id="widget-flickr<?= $modid; ?>" class="widget-inner block-content <?php if($enable_collapse): ?> widget-enanle-collapse collapse in <?php endif; ?>">
<?php
foreach ($photos as $k => $v) {
	?>
	<a class="group-file<?= $userId; ?> flick-photo" href="https://farm<?= $v['farm']; ?>.staticflickr.com/<?= $v['server']; ?>/<?= $v['id']; ?>_<?= $v['secret']; ?>_<?= $popup; ?>.jpg" rel="flick-group-<?= $modid; ?>">
		<img width="<?= $thumbnailImageWidth; ?>" height="<?= $thumbnailImageHeight ?>"  src="https://farm<?= $v['farm']; ?>.staticflickr.com/<?= $v['server']; ?>/<?= $v['id']; ?>_<?= $v['secret']; ?>_<?= $thumbnail; ?>.jpg" />
	</a>
	<?php
}
?>
<script type="text/javascript">
require(['jquery'],function($){
            $(document).ready(function(){
            	require([
					'jquery'
					<?php if($this->helper("Ves\All\Helper\Data")->getConfig("enable_colorbox")): ?>
				    ,"Ves_All/lib/colorbox/jquery.colorbox.min"
				    <?php endif; ?>
					],function($){
						var cboxOptions = {
							width: "<?= "'".$popupImageWidth."'"; ?>",
						  	maxWidth: '960px',
						  	maxHeight: '960px',
						  	initialWidth: 300,
						  	initialHeight: 100
						}
						if(window.innerWidth > 780){
							cboxOptions.initialWidth = 600;
							cboxOptions.initialHeight = 450;
						}
						$('.flick-photo').colorbox({
							overlayClose: true,
							opacity: 0.5,
							rel: 'flick-group-<?= $modid; ?>',
							speed : <?= $speed; ?>,
							maxWidth: '960px',
						  	maxHeight: '960px',
						  	initialWidth: cboxOptions.initialWidth,
						  	initialHeight: cboxOptions.initialHeight,
							width : <?= "'".$popupImageWidth."'"; ?>,
							onLoad:function(){

							}
						});

						jQuery(window).resize(function(){
						    jQuery.colorbox.resize({
						      width: window.innerWidth > parseInt(cboxOptions.maxWidth) ? cboxOptions.maxWidth : cboxOptions.width
						    });
						});
				});
            });
        });
</script>
<?php if($enable_collapse): ?>
<script type="text/javascript">
require(['jquery'],function($){
    $(document).ready(function(){
	require([
		'jquery'
		<?php if($this->helper("Ves\All\Helper\Data")->getConfig("enable_bootstrap_js")): ?>
		,"Ves_All/lib/bootstrap/js/bootstrap.min"
		<?php endif; ?>
		],function($){

		});
	});
});
</script>
<?php endif; ?>
</div>
</div>
