<?php
$custom_url = $this->getConfig("custom_url", "");
if ($width): ?>
<script src="https://apis.google.com/js/platform.js" async defer>{lang: 'nl'}</script>
<div class="ves-widget widget-google-button block <?= $addition_cls; ?> <?php if (isset($stylecls)&&$stylecls) echo 'block-'.$stylecls;?>">
		<?php if (isset($widget_heading)&&!empty($widget_heading)): ?>
		<div class="block-title">
			<h2><span><?= $widget_heading; ?></span></h2>
		</div>
		<?php endif; ?>
		<div class="widget-inner block-content">
			<div class="g-plusone" data-size="<?= $size; ?>" data-annotation="<?= $annotation; ?>" data-width="<?= $width; ?>" <?= $custom_url?'data-href="'.$custom_url.'"':'';?>></div>
		</div>
</div>
<?php endif; ?>
