<div class="ves-widget block block-list block-google-plus">
	<?php if(isset($title) && @trim($title)!=''): ?>
		<div class="block-title">
			<strong><span><?= $title; ?></span></strong>
		</div>
	<?php endif; ?>
	<div class="block-content">
		<div class="<?= $badge; ?>" data-width="<?= $width; ?>" data-annotation="bubble" data-href="<?= $url ?>" data-theme="<?= $theme; ?>" data-showtagline="<?= $tagline ?>" data-showcoverphoto="<?= $coverphoto ?>" data-rel="author" data-layout="<?= $layout ?>"></div>

		<!-- Place this tag after the last widget tag. -->
		<script type="text/javascript">
		  (function() {
		    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
		    po.src = 'https://apis.google.com/js/platform.js';
		    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
		  })();
		</script>
	</div>
</div>
