<?php
/*
* Ves Magento Theme Framework for Prestashop 1.6.x
*
* @package   vesblockbuilder
* @version   5.0
* @author    http://www.venustheme.com
* @copyright Copyright (C) October 2013 venustheme.com <@emai:venustheme@gmail.com>
*               <info@venustheme.com>.All rights reserved.
* @license   GNU General Public License version 2
*/
$id=rand().time();
if(isset($description)) {
	$description = @str_replace(array("\r", "\n"), "", $description);
} else {
	$description = "";
}

?>
<div id="map-canvas<?= $id; ?>" style="width:<?= $width; ?>; height:<?= $height; ?>;"></div>
<script type="text/javascript">
	function loadScript(src,callback){
	    var script = document.createElement("script");
	    script.type = "text/javascript";
	    if(callback)script.onload=callback;
	    document.getElementsByTagName("head")[0].appendChild(script);
	    script.src = src;
	}

    loadScript('https://maps.googleapis.com/maps/api/js?key=<?= $google_api; ?>&v=3&callback=initialize',
              function(){console.log('\n<?= __("ves_base_widget_googlemap: google-loader has been loaded, but not the maps-API.");?>');});

</script>
<script type="text/javascript">
	var map;
    function initialize() {
		try{
			if(typeof(google) != "undefined"){
				var myLatlng = new google.maps.LatLng( <?= (float)$latitude; ?>, <?= (float)$longitude; ?> );
				var mapOptions = {
					zoom: <?= $zoom?(int)$zoom:8; ?>,
					center: myLatlng,
					mapTypeId: google.maps.MapTypeId.ROADMAP
				};

				map = new google.maps.Map(document.getElementById('map-canvas<?= $id; ?>'), mapOptions);
				var marker = new google.maps.Marker({
				            position: myLatlng,
				            map: map,
				            <?php if($maker_icon): ?>
				            icon: "<?= $maker_icon; ?>",
				            <?php endif; ?>
				            title: " "
				           });
				var infowindow = new google.maps.InfoWindow();
			  	infowindow.setContent('<?= $description; ?>');
			  	google.maps.event.addListener(marker, 'click', function() {
			      infowindow.open(map, marker);
			  	});

			}
		}catch(e){

		}
    }
    window.onload = initialize();
</script>

