<?php
	$show_width_height = $this->getConfig("show_wh", 0);
	$alt_text = $this->getConfig("alt_text", "");
?>
<div class="ves-widget ourservice-block block <?= $wrapper_class; ?>">
	<div class="media <?= $inner_class; ?>">
		<?php if($icon_position == 'left' || $icon_position == 'right' || $icon_position == 'top' ){ ?>
		<?php if($icon_class || $thumbnailurl){  ?>
		<div class="<?php if($icon_position == 'left'){ echo 'pull-left'; }elseif($icon_position == 'right'){echo
			'pull-right'; } ?> <?php if (isset($stylecls)&&$stylecls) echo 'text-'.$stylecls;?> <?= $image_class; ?>">
			<?php if($link): ?>
			<a href="<?= $link; ?>">
			<?php endif; ?>
			<?php if($icon_class){ ?>
			<i class="fa <?= $icon_class; ?>" style="<?= (isset($font_size) && $font_size)?'font-size:'.$font_size:''; ?>"></i>
			<?php }elseif($thumbnailurl){ ?>
			<img src="<?= $thumbnailurl; ?>" alt="<?= $alt_text; ?>" <?php if($show_width_height): ?>width="<?= $image_width; ?>" height="<?= $image_height; ?>"<?php endif; ?>/>
			<?php } ?>
			<?php if($link): ?>
			</a>
			<?php endif; ?>
		</div>
		<?php } ?>
		<?php } ?>

		<?php if( $widget_heading != '' || $content != '' ){ ?>
		<?php if( $widget_heading != '' ){ ?>
		<h4 class="ourservice-heading <?= $widget_heading_class; ?>">
			<?php if($link): ?>
			<a href="<?= $link; ?>">
			<?php endif; ?>
			<?= $widget_heading; ?>
			<?php if($link): ?>
			</a>
			<?php endif; ?>
		</h4>
		<?php } ?>
		<?php if( $content != '' ){ ?>
		<div class="ourservice-content <?= $content_class; ?>">
			<?= $content; ?>
		</div>
		<?php } ?>
		<?php } ?>

		<?php if( ($icon_position == 'bottom') && ( $icon_class || $thumbnailurl )){ ?>
		<div <?php if( $image_class != '' ){ echo 'class="'.$image_class.'"'; } ?> >
			<?php if($link): ?>
			<a href="<?= $link; ?>">
			<?php endif; ?>
			<?php if($icon_class){ ?>
			<i class="fa <?= $icon_class ?>"></i>
			<?php }elseif($thumbnailurl){ ?>
			<img src="<?= $thumbnailurl ?>" alt="<?= $alt_text; ?>" <?php if($show_width_height): ?>width="<?= $image_width; ?>" height="<?= $image_height; ?>"<?php endif; ?>/>
			<?php } ?>
			<?php if($link): ?>
			</a>
			<?php endif; ?>
		</div>
		<?php } ?>
	</div>
</div>
