<?php
if ($select_type): ?>
	<div class="ves-widget widget-pinterest block">
		<?php if (isset($widget_heading)&&!empty($widget_heading)): ?>
		<div class="block-title">
			<h2><span><?= $widget_heading; ?></span></h2>
		</div>
		<?php endif; ?>
		<div class="widget-inner block-content">

			<a data-pin-do="buttonPin" <?= $button_type.$color; ?> href="http://www.pinterest.com/pin/create/button/?url=<?= $url;?>&amp;media=<?= $media; ?>&amp;description=<?= $description; ?>"
				class="pin-it-button" data-pin-count="<?= $select_type; ?>">
			    <img src="//assets.pinterest.com/images/pidgets/<?= $color_image?$color_image:'pin_it_button.png';?>" alt="<?= __('Pin It'); ?>" />
			</a>
		</div>
	</div>

	<script type="text/javascript">
		(function(d){
		    var f = d.getElementsByTagName('SCRIPT')[0], p = d.createElement('SCRIPT');
		    p.type = 'text/javascript';
		    p.async = true;
		    p.src = '//assets.pinterest.com/js/pinit.js';
		    f.parentNode.insertBefore(p, f);
		}(document));
	</script>
<?php endif; ?>
