<div class="ves-widget pricing pricing-table <?= $class; ?> <?= $isfeatured?'pricing-highlight':''; ?> text-center">
	<div class="pricing-heading">
		<?php if(isset($widget_heading) && $widget_heading): ?>
		<h4 class="plan-title"><span><?= $widget_heading; ?></span></h4>
		<?php endif; ?>
		<?php if($subtitle): ?>
		<div class="subtitle"><?= $subtitle; ?></div>
		<?php endif; ?>
		<div class="plan-price" ><sup class="plan-currency"><?= $currency; ?></sup> <span class="plan-figure"><?= $price; ?></span> <p class="plan-period"><?= $period; ?></p> </div>
	</div>
	<div class="pricing-body">
		 <div class="plain-info">
			<?= $content; ?>
		</div>
	</div>
	<div class="pricing-footer"><a class="button btn btn-lg btn-block btn-outline <?= $stylecls?'btn-'.$stylecls:''; ?> plan-link" href="<?= $link; ?>"><?= $linktitle;?></a></div>
</div>


