<?php if ($prog_type): ?>
	<div class="ves-widget widget-progress-bar block <?= $addition_cls; ?> <?php if (isset($stylecls)&&$stylecls) echo 'block-'.$stylecls;?>">
		<?php if (isset($widget_heading)&&!empty($widget_heading)): ?>
			<div class="block-title">
				<h2><span><?= $widget_heading; ?></span></h2>
			</div>
		<?php endif; ?>
		<div class="widget-inner block-content">

			<?php if($prog_type == 'progress' || $prog_type == 'progress progress-striped' || $prog_type == 'progress progress-striped active'){ ?>
			<?php if($success) : ?>
			<?php $success = @explode('|',$success) ?>
			<?php if($prog_label){ ?>
			<div class="progress-label"><?= $success[0]; ?></div>
			<?php } ?>
			<div class="<?= $prog_type ; ?>">

				<div class="progress-bar progress-bar-<?= $success[0] ?>" role="progressbar" aria-valuenow="<?= $success[1] ?>" aria-valuemin="<?= $success[2] ?>" aria-valuemax="<?= $success[3] ?>" style="width: <?= $success[1].'%' ?>">
					<?php if($prog_label){
						echo $success[1].'%';
					}else{ ?>
					<span class="sr-only"><?= $success[1].'% '. __('Complete (success)'); ?></span>
					<?php } ?>
				</div>
			</div>
			<?php endif; ?>

			<?php if($info) : ?>
			<?php $info = @explode('|',$info) ?>
			<?php if($prog_label){ ?>
			<div class="progress-label"><?= $info[0]; ?></div>
			<?php } ?>
			<div class="<?= $prog_type ; ?>">
				<div class="progress-bar progress-bar-<?= $info[0] ?>" role="progressbar" aria-valuenow="<?= $info[1] ?>" aria-valuemin="<?= $info[2] ?>" aria-valuemax="<?= $info[3] ?>" style="width: <?= $info[1].'%' ?>">
					<?php if($prog_label){
						echo $info[1].'%';
					}else{ ?>
					<span class="sr-only"><?= $info[1].'% '. __('Complete'); ?></span>
					<?php } ?>
				</div>
			</div>
			<?php endif; ?>

			<?php if($warning) : ?>
			<?php $warning = @explode('|',$warning) ?>
			<?php if($prog_label){ ?>
			<div class="progress-label"><?= $warning[0]; ?></div>
			<?php } ?>
			<div class="<?= $prog_type ; ?>">
				<div class="progress-bar progress-bar-<?= $warning[0] ?>" role="progressbar" aria-valuenow="<?= $warning[1] ?>" aria-valuemin="<?= $warning[2] ?>" aria-valuemax="<?= $warning[3] ?>" style="width: <?= $warning[1].'%' ?>">
					<?php if($prog_label){
						echo $warning[1].'%';
					}else{ ?>
					<span class="sr-only"><?= $warning[1].'% '. __('Complete'); ?></span>
					<?php } ?>
				</div>
			</div>
			<?php endif; ?>

			<?php if($danger) : ?>
			<?php $danger = @explode('|',$danger) ?>
			<?php if($prog_label) : ?>
			<div class="progress-label"><?= $danger[0]; ?></div>
			<?php endif; ?>
			<div class="<?= $prog_type ; ?>">
				<div class="progress-bar progress-bar-<?= $danger[0] ?>" role="progressbar" aria-valuenow="<?= $danger[1] ?>" aria-valuemin="<?= $danger[2] ?>" aria-valuemax="<?= $danger[3] ?>" style="width: <?= $danger[1].'%' ?>">
					<?php if($prog_label){
						echo $danger[1].'%';
					}else{ ?>
					<span class="sr-only"><?= $danger[1].'% '. __('Complete (danger)'); ?></span>
					<?php } ?>
				</div>
			</div>
			<?php endif; ?>
			<?php }elseif($prog_type == 'stacked'){ ?>

			<div class="progress progress-striped active">

				<?php if($success) : ?>
				<?php $success = @explode('|',$success) ?>
				<div class="progress-bar progress-bar-<?= $success[0] ?>" role="progressbar" aria-valuenow="<?= $success[1] ?>" aria-valuemin="<?= $success[2] ?>" aria-valuemax="<?= $success[3] ?>" style="width: <?= $success[1].'%' ?>">
					<?php if($prog_label){
						echo $success[1].'%';
					}else{ ?>
					<span class="sr-only"><?= $success[1].'% '. __('Complete (success)'); ?></span>
					<?php } ?>
				</div>
				<?php endif; ?>

				<?php if($info) : ?>
				<?php $info = @explode('|',$info) ?>
				<div class="progress-bar progress-bar-<?= $info[0] ?>" role="progressbar" aria-valuenow="<?= $info[1] ?>" aria-valuemin="<?= $info[2] ?>" aria-valuemax="<?= $info[3] ?>" style="width: <?= $info[1].'%' ?>">
					<?php if($prog_label){
						echo $info[1].'%';
					}else{ ?>
					<span class="sr-only"><?= $info[1].'% '. __('Complete'); ?></span>
					<?php } ?>
				</div>
				<?php endif; ?>

				<?php if($warning) : ?>
				<?php $warning = @explode('|',$warning) ?>
				<div class="progress-bar progress-bar-<?= $warning[0] ?>" role="progressbar" aria-valuenow="<?= $warning[1] ?>" aria-valuemin="<?= $warning[2] ?>" aria-valuemax="<?= $warning[3] ?>" style="width: <?= $warning[1].'%' ?>">
					<?php if($prog_label){
						echo $warning[1].'%';
					}else{ ?>
					<span class="sr-only"><?= $warning[1].'% '. __('Complete'); ?></span>
					<?php } ?>
				</div>
				<?php endif; ?>

				<?php if($danger) : ?>
				<?php $danger = @explode('|',$danger) ?>
				<div class="progress-bar progress-bar-<?= $danger[0] ?>" role="progressbar" aria-valuenow="<?= $danger[1] ?>" aria-valuemin="<?= $danger[2] ?>" aria-valuemax="<?= $danger[3] ?>" style="width: <?= $danger[1].'%' ?>">
					<?php if($prog_label){
						echo $danger[1].'%';
					}else{ ?>
					<span class="sr-only"><?= $danger[1].'% '. __('Complete (danger)'); ?></span>
					<?php } ?>
				</div>
				<?php endif; ?>
			</div>
			<?php } ?>
		</div>
	</div>
<?php endif; ?>
