<div class="ves-widget block block-list block-review-rotator">
	<?php if(@trim($title)!=''): ?>
		<div class="block-title">
			<strong><span><?= $title; ?></span></strong>
		</div>
	<?php endif; ?>
	<div class="block-content">
		<ol style="margin-top:15px;">
			<?php foreach ($reviews as $review) { ?>
			<li>
				<a href="<?= $review['product']['url']; ?>"><strong><?= $review['product']['name']; ?></strong></a>
				<?php if($author){ ?>
				<br> <?= __("Review by ");?><?= $review['author']['name'];?>
				<?php } ?>
				<table class="rr-ratings-list" cellspacing="0">
					<tbody>
						<?php foreach ($review['rating'] as $rating) { ?>
						<tr>
							<td class="label"><strong><?= $rating['name']; ?></strong></td>
							<td>
								<div class="rating-box">
									<div class="rating" style="width: <?= $rating['percent'] ?>%;"></div>
								</div>
							</td>
						</tr>
						<?php } ?>
					</tbody>
				</table>
				<p>
					<?php if($reviewTitle){ ?>
					<strong><a href="<?= $review['review']['url']; ?>" target="_blank"><?= $review['review']['title']; }?></a></strong>
					<?php } ?>
					<?php if($description){ ?>
					<br><?= $review['review']['description']; ?>(<?= __("Posted on ");?><?= $review['review']['created_at'] ?>)</p>
					<?php } ?>
				</li>
			</ol>
		</div>
	</div>
