<?php
$id = rand().time();
$current_date = $this->getConfig('show_current_date',0);
$expired_date = $this->getConfig('end_date','');
if($current_date){
?>
<div id="day-countdown<?php echo $id; ?>" class="countdown-timer"><p></p></div>
<script type="text/javascript" xml="space">
require(['jquery',function ($) {

    setInterval(function time(){
        var d = new Date();
        var hours = 24 - d.getHours();
        var min = 60 - d.getMinutes();
        if((min + '').length == 1){
            min = '0' + min;
        }
        var sec = 60 - d.getSeconds();
        if((sec + '').length == 1){
                sec = '0' + sec;
        }
        jQuery('#day-countdown<?php echo $id; ?> p').html(hours+':'+min+':'+sec)
    }, 1000);

});
</script>
<?php } elseif($end_date) {
    $date1 = date('G:i:s', strtotime($end_date));
    if ($date1 == "0:00:00") {
        $targetDate = date('m/d/Y \2\3\:\5\9\:\0\0', strtotime($end_date));
    }else{
        $targetDate = date('m/d/Y G:i:s', strtotime($end_date));
    }
    ?>
<div class="banner-countdowns">
    <div id="flashsale<?php echo $id; ?>countdown" class="item-countdown">
        <ul>
            <li>%%D%% <div><?php echo __('Day');?></div></li>
            <li> %%H%% <div><?php echo __('Hours');?></div></li>
            <li> %%M%% <div><?php echo __('Mins');?></div></li>
            <li> %%S%% <div><?php echo __('Secs');?></div></li>
        </ul>
    </div>
    <script type="text/javascript">
        require(['jquery','Ves_BaseWidget/js/countdown'],function ($) {
            jQuery("#flashsale<?php echo $id; ?>countdown").lofCountDown({
                    formatStyle:2,
                    TargetDate:"<?php echo $targetDate; ?>",
                    countdownFormat: "#flashsale<?php echo $id; ?>countdown",
                    DisplayFormat: jQuery("#flashsale<?php echo $id; ?>countdown").html(),
                    FinishMessage:"<?php echo __('Expired');?>"
            });

        });
    </script>
</div>
    <?php
}
?>