<?php
	$modid = rand().time();
	$enable_collapse = $this->getConfig("enable_collapse", 0);
?>
<div class="ves-widget widget-sociallinks block">
	<?php if (isset($widget_heading)&&!empty($widget_heading)): ?>
	<div class="block-title">
		<?php if($enable_collapse): ?><span class="opener hidden-lg hidden-md" data-toggle="collapse" data-target="#widget-sociallinks<?= $modid; ?>"><i class="fa fa-angle-down"></i></span><?php endif; ?>
		<h2><span><?= $widget_heading; ?></span></h2>
	</div>
	<?php endif; ?>
	<div id="widget-sociallinks<?= $modid; ?>" class="widget-inner block-content <?php if($enable_collapse): ?> widget-enanle-collapse collapse in <?php endif; ?>">
		<ul>
			<?php
			if($facebook_link){ ?>
			<li class="facebook"><a class="fa fa-facebook" href="<?= 'http://facebook.com/'.$facebook_link ?>" title="<?= __("Facebook"); ?>"></a></li>
			<?php } ?>
			<?php
			if($twitter_link){ ?>
			<li class="twitter"><a class="fa fa-twitter" href="<?= 'https://twitter.com/'.$twitter_link ?>" title="<?= __("Twitter"); ?>"></a></li>
			<?php } ?>
			<?php
			if($pinterest_link){ ?>
			<li class="pinterest"><a class="fa fa-pinterest" href="<?= 'https://pinterest.com/'.$pinterest_link ?>" title="<?= __("Pinterest"); ?>"></a></li>
			<?php } ?>
			<?php
			if($google_plus){ ?>
			<li class="google-plus"><a class="fa fa-google-plus" href="<?= 'https://plus.google.com/'.$google_plus ?>" title="<?= __("Google Plus"); ?>"></a></li>
			<?php } ?>
			<?php
			if($youtube){ ?>
			<li class="youtube"><a class="fa fa-youtube" href="<?= 'https://youtube.com/'.$youtube ?>" title="<?= __("Youtube"); ?>"></a></li>
			<?php } ?>
			<?php
			if($skype){ ?>
			<li class="skype"><a class="fa fa-skype" href="<?= 'https://skype.com/'.$skype ?>" title="<?= __("Skype"); ?>"></a></li>
			<?php } ?>
			<?php
			if($vimeo){ ?>
			<li class="vimeo"><a class="fa fa-vimeo-square" href="<?= 'https://vimeo.com/'.$vimeo ?>" title="<?= __("Vimeo"); ?>"></a></li>
			<?php } ?>
			<?php
			if($instagram){ ?>
			<li class="instagram"><a class="fa fa-instagram" href="<?= 'https://instagram.com/'.$instagram ?>" title="<?= __("Instagram"); ?>"></a></li>
			<?php } ?>
			<?php
			if($linkedin){ ?>
			<li class="linkedin"><a class="fa fa-linkedin" href="<?= 'https://linkedin.com/'.$linkedin ?>" title="<?= __("Linkedin"); ?>"></a></li>
			<?php } ?>
			<?php
			if(isset($fivepx) && $fivepx){ ?>
			<li class="fivepx"><a class="fa fa-500px" href="<?= 'https://500px.com/'.$fivepx ?>" title="<?= __("500px"); ?>"></a></li>
			<?php } ?>
			<?php
			if(isset($amazon) && $amazon){ ?>
			<li class="amazon"><a class="fa fa-amazon" href="<?= 'http://www.amazon.com/'.$amazon ?>" title="<?= __("Amazon"); ?>"></a></li>
			<?php } ?>
			<?php
			if(isset($weibo) && $weibo){ ?>
			<li class="weibo"><a class="fa fa-weibo" href="<?= 'http://weibo.com/'.$weibo ?>" title="<?= __("Weibo"); ?>"></a></li>
			<?php } ?>
			<?php
			if(isset($reddit) && $reddit){ ?>
			<li class="reddit"><a class="fa fa-reddit" href="<?= 'https://reddit.com/'.$reddit ?>" title="<?= __("Reddit"); ?>"></a></li>
			<?php } ?>
			<?php
			if(isset($vine) && $vine){ ?>
			<li class="vine"><a class="fa fa-vine" href="<?= 'https://vine.co/'.$vine ?>" title="<?= __("Vine"); ?>"></a></li>
			<?php } ?>
			<?php
			if(isset($whatsapp) && $whatsapp){ ?>
			<li class="whatsapp"><a class="fa fa-whatsapp" href="whatsapp://send?text=<?= $block->escapeHtml($whatsapp) ?>" title="<?= __("Whatsapp"); ?>"></a></li>
			<?php } ?>
			<?php
			if(isset($tumblr) && $tumblr){ ?>
			<li class="tumblr"><a class="fa fa-tumblr" href="<?= 'https://www.tumblr.com/'.$tumblr ?>" title="<?= __("Tumblr"); ?>"></a></li>
			<?php } ?>
			<?php
			if(isset($foursquare) && $foursquare){ ?>
			<li class="foursquare"><a class="fa fa-foursquare" href="<?= 'https://foursquare.com/'.$foursquare ?>" title="<?= __("Foursquare"); ?>"></a></li>
			<?php } ?>
			<?php
			if(isset($dribbble) && $dribbble){ ?>
			<li class="dribbble"><a class="fa fa-dribbble" href="<?= 'https://dribbble.com/'.$dribbble ?>" title="<?= __("Dribbble"); ?>"></a></li>
			<?php } ?>
			<?php
			if(isset($behance) && $behance){ ?>
			<li class="behance"><a class="fa fa-behance" href="<?= 'https://www.behance.net/'.$behance ?>" title="<?= __("Behance"); ?>"></a></li>
			<?php } ?>
			<?php
			if(isset($delicious) && $delicious){ ?>
			<li class="delicious"><a class="fa fa-delicious" href="<?= 'http://delicious.com/'.$delicious ?>" title="<?= __("Delicious"); ?>"></a></li>
			<?php } ?>
			<?php
			if(isset($slideshare) && $slideshare){ ?>
			<li class="slideshare"><a class="fa fa-slideshare" href="<?= 'http://slideshare.net/'.$slideshare ?>" title="<?= __("Slideshare"); ?>"></a></li>
			<?php } ?>
			<?php
			if(isset($steam) && $steam){ ?>
			<li class="steam"><a class="fa fa-steam" href="<?= 'http://store.steampowered.com/'.$steam ?>" title="<?= __("Steam"); ?>"></a></li>
			<?php } ?>
			<?php
			if(isset($yelp) && $yelp){ ?>
			<li class="yelp"><a class="fa fa-yelp" href="<?= 'http://www.yelp.com/'.$yelp ?>" title="<?= __("Yelp"); ?>"></a></li>
			<?php } ?>
			<?php
			if(isset($flickr) && $flickr){ ?>
			<li class="flickr"><a class="fa fa-flickr" href="<?= 'https://www.flickr.com/'.$flickr ?>" title="<?= __("Flickr"); ?>"></a></li>
			<?php } ?>
		</ul>
	</div>
</div>
<?php if($enable_collapse): ?>
<script type="text/javascript">
require(['jquery'],function($){
    $(document).ready(function(){
	require([
		'jquery'
		<?php if($this->helper("Ves\All\Helper\Data")->getConfig("enable_bootstrap_js")): ?>
		,"Ves_All/lib/bootstrap/js/bootstrap.min"
		<?php endif; ?>
		],function($){

		});
	});
});
</script>
<?php endif; ?>
