<?php
$id = $this->getData('id');
$title = $this->getData('title');

$modid = rand().time();
$enable_collapse = $this->getConfig("enable_collapse", 0);
$aspect_ratio = $this->getConfig("aspect_ratio", "16by9");
?>
<div class="ves-widget block block-list block-youtube-widget">
	<?php if(isset($title) && @trim($title)!=''): ?>
		<div class="block-title">
			<?php if($enable_collapse): ?><span class="opener hidden-lg hidden-md" data-toggle="collapse" data-target="#widget-youtube<?= $modid; ?>"><i class="fa fa-angle-down"></i></span><?php endif; ?>
			<strong><span><?= $title; ?></span></strong>
		</div>
	<?php endif; ?>
	<div id="widget-youtube<?= $modid; ?>" class="widget-inner block-content <?php if($enable_collapse): ?> widget-enanle-collapse collapse in <?php endif; ?>">
		<?php if(!$image_file){ ?>
		<div class="embed-responsive embed-responsive-<?= $aspect_ratio; ?>">
		<iframe class="embed-responsive-item" width="<?= $width ?>" height="<?= $height ?>" src="//www.youtube.com/embed/<?= $id; ?>" style="border:0px solid" allowfullscreen="allowfullscreen"></iframe>
		</div>
		<?php }else{ ?>

		<div class="video-widget-bg" onclick="playVideo<?= $modid; ?>()" style="height: <?= $height.'px' ?>; width: <?= $width.'px' ?>; background: black url('<?= $thumbnailurl ?>') no-repeat center; -webkit-background-size: cover; -moz-background-size: cover; -o-background-size: cover; background-size: cover; overflow: hidden; cursor: pointer;"><div id="vidwrap<?= $modid; ?>" class="embed-responsive embed-responsive-<?= $aspect_ratio; ?>"></div></div>
<script type="text/javascript">// <![CDATA[
	function playVideo<?= $modid; ?>(){
	document.getElementById('vidwrap<?= $modid; ?>').innerHTML = '<iframe class="embed-responsive-item" width="<?= $width ?>" height="<?= $height ?>" src="//www.youtube.com/embed/<?= $this->getData("id"); ?>?autoplay=1&#038;showinfo=0" frameborder="0"></iframe>';}
	document.getElementById("vidwrap<?= $modid; ?>").addEventListener("click", playVideo<?= $modid; ?>);
	// ]]> </script>

	<?php } ?>

</div>
</div>
<?php if($enable_collapse): ?>
<script type="text/javascript">
require(['jquery'],function($){
    $(document).ready(function(){
	require([
		'jquery'
		<?php if($this->helper("Ves\All\Helper\Data")->getConfig("enable_bootstrap_js")): ?>
		,"Ves_All/lib/bootstrap/js/bootstrap.min"
		<?php endif; ?>
		],function($){

		});
	});
});
</script>
<?php endif; ?>

